
// NOTE: This is no "include once" guard for this header!
// This is intentional!

#if defined(_RCC_THIRDPARTY_WARNINGS_DISABLED)
#error ERROR: _RCC_THIRDPARTY_WARNINGS_DISABLED is defined. #include <thirdparty_disable_warnings.h> and <thirdparty_restore_warnings.h> mismatch!
#else
#define _RCC_THIRDPARTY_WARNINGS_DISABLED
#endif

// Disable all warnings generated by third-party libraries

#ifdef _MSC_VER

#pragma warning (push)

// 'conversion' conversion from 'type1' to 'type2', possible loss of data
// See: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244
#pragma warning (disable: 4244)

#endif
